name: CI Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mariadb:10.6
        env:
          MARIADB_ROOT_PASSWORD: 'root'
        ports:
          - 3306:3306

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup environment and run tests
      run: |
        wget -q https://raw.githubusercontent.com/frappe/erpnext/develop/.github/helper/install.sh
        chmod +x install.sh
        DB=mariadb TYPE=server ./install.sh
        cd ~/frappe-bench
        bench --site test_site run-tests --app financed_sales
